# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "usbhid" "usb_storage" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6d2c02f4-d20a-4f25-ba47-5287138ee7cd";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/23814d8d-41aa-4729-ad26-d922ea2800a7"; }
      { device = "/dev/disk/by-uuid/97d0d40e-4b08-494c-b73b-a1d7c51db0ea"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
